import Link from 'next/link'
import Head from 'next/head'

function Index() {
  return (
    <div className='center'>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Luca</h1>
      <Link href='/login'>
            <button>Login</button>
        </Link>
      <Link href='/signup'>
            <button>Sign Up</button>
        </Link>
    </div>
  )
}

export default Index