import Header from '../components/core/Header'
import Create from '../components/pages_components/Create'
import Footer from '../components/core/Footer'
import Head from 'next/head';

export default function create() {
  return (
    <div>
      <Head>
        <title>Create</title>
        <meta name="create" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header title={'CREATE'} />
        <Create />
        <Footer activeNow='CREATE'/>
    </div>
  )
}