import Header from '../components/core/Header'
import Homepage from '../components/pages_components/Homepage'
import Footer from '../components/core/Footer'
import Head from 'next/head';

function homepage() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="home" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={'HOMEPAGE'} />
      <Homepage />
      <Footer activeNow='HOMEPAGE'/>
    </div>
  )
}

export default homepage