import Index from "../components/pages_components/Index"
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="index" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index />
    </div>
  )
}