import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Luca</h1>
      <Link href='/login'>
            <button>Login</button>
        </Link>
      <Link href='/signup'>
            <button>Sign Up</button>
        </Link>
    </div>
  )
}
