import Head from 'next/head';
import Header from '../components/core/Header';
import Login from '../components/pages_components/Login';

function login() {
  return (
    <div>
        <Head>
          <title>Login</title>
          <meta name="login" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Login />
    </div>
  )
}

export default login