import Header from '../components/core/Header';
import Profile from '../components/pages_components/Profile';
import Footer from '../components/core/Footer'
import Head from 'next/head';

function profile() {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="profile" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={'PROFILE'}/>
      <Profile />
      <Footer activeNow={'PROFILE'}/>
    </div>
  )
}

export default profile