import Header from '../components/core/Header'
import Footer from '../components/core/Footer'
import Head from 'next/head';
import Search from '../components/pages_components/Search';
import axios from 'axios';
import { GetServerSideProps } from 'next';

export default function search({users}) {

  console.log(users);
  return (
    <div>
        <Head>
        <title>Search</title>
        <meta name="search" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header showBackArrow={true} title={undefined} username={"Search"}/>
        <Search users={users}/>
        <Footer activeNow='SEARCH'/>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {

  const baseURL = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const config = {
    headers:{
      apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
      Authorization: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    }
  };
  const {data} = await axios.get(`${baseURL}/rest/v1/user_data?select=*&order=ideas.desc`,config);

  console.log(data);
  

  return {props: {users: data}}
}

