import Header from '../components/core/Header'
import Footer from '../components/core/Footer'
import Head from 'next/head';
import Search from '../components/pages_components/Search';

function search() {
  return (
    <div>
        <Head>
        <title>Search</title>
        <meta name="search" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header title={'SEARCH'} />
        <Search />
        <Footer activeNow='SEARCH'/>
    </div>
  )
}

export default search