import Header from "../components/core/Header"
import Settings from "../components/pages_components/Settings"
import Head from 'next/head';

function settings() {
  return (
    <div>
      <Head>
        <title>Settings</title>
        <meta name="settings" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <Settings />
    </div>
  )
}

export default settings