import Header from '../components/core/Header'
import Signup from '../components/pages_components/Signup'
import Head from 'next/head';

function signup() {
  return (
    <div>
      <Head>
        <title>Sign Up</title>
        <meta name="signup" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <Signup />
    </div>
  )
}

export default signup